name: My First Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Install dependencies
      run: |
        cd .github/
        npm install
    - name: customer action
      uses: gayathrik92/buisnessgreetings/.github/actions/businessgreetings@main
